### ISSUE TITLE
Truth value of an array with more than one element (line 130)

### ISSUE THREAD

**Issue by mengyaoxue** [gheald/RMtoolkit#1]
When running with numpy version 1.13.3 (on Galaxy), get this error :
------
> p.rmsynthesis(phi_axis)
  File "RMtoolkit/rm.py", line 130, in rmsynthesis
    if self.ierr == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by gheald** [comment]
Hi Mengyao, can you describe the data that you're using? Have you provided uncertainties for the IQU measurements?

**Comment by mengyaoxue** [comment]
Hi Geroge, sorry for my late reply. Yes uncertainties for the IQU measurements are provided in the data (see attached).
[J1752_p3c2_n512_ch124_QUVflux.txt](https://github.com/gheald/RMtoolkit/files/1926451/J1752_p3c2_n512_ch124_QUVflux.txt)

It works fine with older versions of numpy on my own computer
I guess newer numpy is more strick when trying to compare an array with a boolean value

**Comment by gheald** [comment]
I believe that this should be fixed in d73ddb2a19dd223718de04258a1793369e307b2b
